set nocompatible
set encoding=utf-8
set mouse=a

" Styling
syntax on

set showmatch

set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set smartindent
set autoindent

set number
set relativenumber

set cursorline

" Tab completion
set wildmode=longest,list,full
set wildmenu

" Searching
set incsearch
set hlsearch

" Completion stuff
filetype plugin on
set completeopt=menu,menuone,noselect

inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<CR>"
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <Nul> <C-x><C-o>

" Better keybindings for gettings out of modes
inoremap kj <esc>
vnoremap kj <esc>

" Better keybindings for buffer management
nnoremap <Tab> :bnext<CR>
nnoremap <S-Tab> :bprevious<CR>

" Better keybindings for yanking/pasting to/from system clipboard
nnoremap <Leader>p "+p
vnoremap <Leader>p "+p

nnoremap <Leader>y "+y
vnoremap <Leader>y "+y

" Better keybindings for navigating splits
nnoremap <C-h> <C-W>h
nnoremap <C-j> <C-W>j
nnoremap <C-k> <C-W>k
nnoremap <C-l> <C-W>l

" Netrw configs
let g:netrw_liststyle=3 " Tree View
let g:netrw_preview=1 " Open previews in vertical split
let g:netrw_alto=0 " Open previews in vertical split to right
let g:netrw_altv=1 " Right split when opening file
let g:netrw_keepdir=0 " netrw to open relative to cwd, rather than where vim was started

nnoremap <Leader>e :Explore .<CR>

" Setup cold folding. Use space bar to fold. Folds should save when closing buffer
set foldmethod=indent
set foldlevel=99
nnoremap <space> za

augroup remember_folds
    autocmd!
    autocmd BufWinLeave * mkview
    autocmd BufWinEnter * silent! loadview
augroup END

" Pull in my other vim files
source ~/Documents/repos/dotfiles/vim/dracula_colors.vim
source ~/Documents/repos/dotfiles/vim/git_magic.vim
source ~/Documents/repos/dotfiles/vim/status_line.vim
source ~/Documents/repos/dotfiles/vim/fuzzy_finder.vim
